x-env_file:
  &env-file
  env_file:
    - ./.env
    - ./.env.${NODE_ENV}

x-network:
  &network
  networks:
    - postgres-network

x-restart-policy:
  &restart-policy
  restart: always

services:
  database:
    <<: [*env-file, *network, *restart-policy]
    build:
      context: .
      dockerfile: ./Database.Dockerfile
      args:
        - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER}"
      interval: 1s
      timeout: 1s
      retries: 60

  bot:
    <<: [*env-file, *network, *restart-policy]
    environment:
      - NODE_ENV=${NODE_ENV}
    build:
      context: .
      dockerfile: ./Dockerfile
    command: dotenvx run --convention=nextjs -- yarn start
    volumes:
      - bot_logs:/var/log/datadrop/
    depends_on:
      database:
        condition: service_healthy

volumes:
  postgres:
  bot_logs:

networks:
  postgres-network:
